app/controllers/top_controller.rb
app/views/top/index.html.haml
spec/requests/top_request_spec.rb

トップページに新着ノート一覧（すべてのユーザーのノート）を追加

トップページに新着ノート一覧を追加/SB-114

---

app/views/navbar/_navbar.html.haml

ロゴにトップページへのリンクを貼る/SB-119

---

app/views/my_lists/index.html.haml
app/views/notes/index.html.haml
app/views/users/my_lists/index.html.haml
app/views/users/notes/index.html.haml
config/locales/views.ja.yml

Add and modify sort types/sb 126

---

app/controllers/my_lists_controller.rb
app/javascript/stylesheets/my-lists.scss
app/models/my_list.rb
app/views/my_lists/index.html.haml

マイリストの検索機能を追加した。といっても部分テンプレートとかわかってないから
それっぽいところコピペしてbodyをdescriptionに変えただけ。

マイリスト検索機能の追加(SB-93)

---

app/controllers/users/notes_controller.rb
app/helpers/directory_tree_helper.rb
app/javascript/packs/application.js
app/javascript/packs/directory_tree.js
app/javascript/packs/my_lists.js
app/javascript/packs/note.js
app/javascript/packs/search.js
app/javascript/packs/search_tags.js
app/javascript/stylesheets/directory-tree.scss
app/javascript/stylesheets/notes.scss
app/views/users/notes/_note_index.html.haml
app/views/users/notes/index.html.haml
app/views/users/notes/index.js.erb

Pagyの導入に対応してAjax時のURLを修正(SB-118)

---

app/controllers/users/notes_controller.rb
app/views/users/notes/_note_index.html.haml
app/views/users/notes/index.html.haml

ユーザのノートに検索機能を追加/(SB-95)

---

app/controllers/users/my_lists_controller.rb
app/views/users/my_lists/index.html.haml

マイリストに検索機能を追加/(SB-96)

---

app/controllers/users_controller.rb
app/helpers/directory_tree_helper.rb
app/influxdb/study_log.rb
app/javascript/packs/application.js
app/javascript/packs/user_notes_category_ratio_graph.js
app/javascript/stylesheets/user.scss
app/models/note.rb
app/views/users/show.html.haml
config/locales/views.ja.yml
config/routes.rb
package.json
spec/influxdb/study_log_spec.rb
spec/models/note_spec.rb
spec/requests/users_request_spec.rb
yarn.lock

ユーザ情報の追加(SB-141)

---

app/javascript/packs/my_lists.js
app/javascript/packs/user_notes_category_ratio_graph.js
config/webpacker.yml
docker-compose.prc.yml

本番環境へ対応(SB-148)

---

app/javascript/stylesheets/note.scss

関連するノートデザインが崩れることがある(SB-154)

---

app/javascript/packs/views/manual.js
app/javascript/stylesheets/application.scss
app/views/information/manual.html.haml
config/webpacker.yml

分割不可能と判断し修正(SB-156)

---

app/views/my_lists/index.html.haml
app/views/notes/_note_index.html.haml
app/views/users/my_lists/index.html.haml
app/views/users/notes/_note_index.html.haml
config/locales/ja.yml
config/locales/views.ja.yml

ノートがない場合のメッセージを追加(SB-128)

---

config/webpack/development.js
config/webpack/environment.js

webpackの設定を変更(SB-168)

---

app/javascript/stylesheets/top.sass
app/views/top/shared/_notes.html.haml

トップページのノートのデザインを修正（SB-169)

---

app/influxdb/study_log.rb

measurementが無いので動かなくなる。
その問題を例外処理で修正

Influxdbののデータがない場合動くように修正(SB-172)

---

app/javascript/stylesheets/left.scss
app/javascript/stylesheets/new-my-list.scss
app/views/my_lists/index.html.haml
app/views/notes/index.html.haml
app/views/users/my_lists/index.html.haml
app/views/users/notes/index.html.haml

influxdbのエラーを修正。
プルダウンリストのデザイン崩れも修正。

Influxdbの修正など(SB-174)

---

app/controllers/top_controller.rb
app/javascript/stylesheets/top.sass
app/views/top/shared/_my_lists.html.haml
config/locales/views.ja.yml

Topページの文字サイズが違う問題を修正(SB-178)

---

app/controllers/users/sessions_controller.rb

サインイン後に特定のパラメータがあるとマニュアルページにリダイレクトする

サインイン後のリダイレクト先の分岐を追加/SB-171

---

app/helpers/directory_tree_helper.rb

ディレクトリ名変更(SB-181)

---

app/views/my_lists/show.html.haml

マイリストの削除ボタンを修正(SB-185)
